site_name: State of Mayflower Legislation
site_url: https://KarlXYZ.github.io/mayflower-docs2/
site_author: KarlXYZ
site_description:

# Repository
repo_name: KarlXYZ/mayflower-docs2
repo_url: https://github.com/KarlXYZ/mayflower-docs2
edit_uri: ""

# nav:
#   - Home: index.md
#   - About: about.md
#   - State Law:
#     - Constitution: constitution/constitution.md
#     - Acts of Congress: acts-of-congress/index.md

theme:
  name: material
  features:
    - tabs

  logo: assets/logo.png
  favicon: assets/favicon.ico

  include_search_page: false
  search_index_only: true

  language: en

plugins:
  - search:
      separator: '[\s\-]+'
  - awesome-pages

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
- stylesheets/extra.css
